# [server]
# headless = true
# port = 8501
# enableCORS = false
# [theme]
# base="dark"
# primaryColor="#1DB954"
# backgroundColor="#0E1117"
# secondaryBackgroundColor="#262730"
# textColor="#FAFAFA"

[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#1DB954"  # салатовый акцент (в стиле Spotify / MAIB)
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

